### ISSUE TITLE
Should verification be a MUST?

### ISSUE THREAD

**Issue by kevinmarks** [aaronpk/webmention#12]
The current spec says:

> 2. The receiver SHOULD perform a HTTP GET request on source to confirm that it actually links to target (note that the receiver will need to check the Content-type of the entity returned by source to make sure it is a textual response).

Making this a MUST seems a clearer statement of intent for the protocol. Posting unverified links is the Trackback problem.

**Comment by csarven** [comment]
If target previously established trust with source, the verification step may not necessarily happen. That's just one counter reason as to why it can't be forced in practice.

If target announces the mentions it receives without verifying, it is their decision because they ultimately control what to publish. This is always the case regardless of what the spec says.

With respect to the verification process, keeping it as is - SHOULD - is fine.

**Comment by aaronpk** [comment]
The other problem with saying verification is a MUST is that it requires the receiver to do work they may not want/need to do. If the receiver blacklists a domain, for example, they may just drop it on the floor.

I think what @kevinmarks is getting at is more along these lines:

> If the receiver is going to use the webmention in some way, (displaying it as a comment on a post, incrementing a "like" counter, notifying the author of a post,) then it MUST perform an HTTP GET request on the source URL to confirm that it actually links to the target.

How does that sound? I would like to bring this up in the call next week regardless.

**Comment by kevinmarks** [comment]
That sounds like a good phrasing.

**Comment by aaronpk** [comment]
Done: https://indiewebcamp.com/wiki/index.php?title=Webmention&diff=23676&oldid=23674

**Comment by aaronpk** [comment]
Closing this as complete based on [today's call](https://www.w3.org/wiki/Socialwg/2015-12-08-minutes#Summary_of_Resolutions)
