### ISSUE TITLE
Location of returned webmention URL

### ISSUE THREAD

**Issue by rhiaro** [aaronpk/webmention#23]
> The webmention endpoint will validate and process the request, and return an HTTP status code. Most often, 202 Accepted will be returned, indicating that the request is queued and being processed asynchronously to prevent DoS attacks. The response body SHOULD include a URL that can be used to monitor the status of the request.

-> The `Location` header SHOULD include a URL that can be used to monitor the status of the request, response body MAY contain this URL?

**Comment by aaronpk** [comment]
s/Location/Link/

**Comment by rhiaro** [comment]
rel value?

**Comment by aaronpk** [comment]
rel=status is a thing, but it's unclear whether that's what its intention is: http://microformats.org/wiki/existing-rel-values

**Comment by aaronpk** [comment]
Turns out rel=status was meant to be used on someone's home page and point to a place to find "status updates" the same way you'd link to a feed of blog posts. http://web.archive.org/web/20121231100232/http://monkinetic.com/2009/11/24/status-autodiscovery-relstatus.html

I'm pretty sure this isn't a common use case anymore (the post was written shortly after Twitter launched) and I'm tempted to just repurpose `rel=status` for this purpose. Alternately I could do `rel=webmention-status`, I don't really care much either way.

**Comment by kevinmarks** [comment]
Why not Location? That's supposed to be where you check on the resource, surely.

**Comment by aaronpk** [comment]
The Location header is only valid on HTTP 201, not 202.

**Comment by aaronpk** [comment]
If you want to be pedantic, HTTP 201 would be an acceptable response since it would indicate that the webmention status object was created, and then the Location header would point to the resource (status of the webmention) that was created. An alternate version of this edit could be to say that if you are storing the status of the webmention in a way where the sender can check on it, then you should return 201 and the Location header. That means if you return 202, the client shouldn't expect to have a way to check the status of it.

**Comment by aaronpk** [comment]
Updated to include explicit 200/201/202 response codes: https://indiewebcamp.com/wiki/index.php?title=Webmention&diff=23665&oldid=23661

**Comment by aaronpk** [comment]
@rhiaro can you review the updated explicit text and let me know if that addresses your concern? http://webmention.net/draft/#receiving-webmentions

**Comment by aaronpk** [comment]
confirmed in person
