### ISSUE TITLE
Consider as:Activity as payload

### ISSUE THREAD

**Issue by azaroth42** [aaronpk/webmention#4]
Being able to transfer an Activity description (to be embedded in an ActivityStream, for example) would be great for integration.  As AS has its own content-type, there would be no confusion as to what the payload consists of.

As an strawperson proposal, systems MUST support www-form-encoded, and SHOULD support AS?

This gives an extension point in the future if there are further syntaxes that can also carry the same information (perhaps with additional structure that's impossible in form-encoded), while still establishing form-encoded as the lingua franca for the 99% simple cases.

**Comment by kevinmarks** [comment]
The key point of webmention is that it points to a source URL for the mention. That certainly could be an as:Activity - it is up to the recipient as to how much information they extract from the source and what they display.

**Comment by aaronpk** [comment]
We saw something similar to this with Trackback, where the actual comment text was sent in the Trackback payload. The issue was that it was quickly overrun by spam since there was no verification step. In order to support sending actual content in the payload, you'd have to have some sort of authentication or signature method, which is definitely a different spec. Like Kevin said, the document at the source URL could definitely be an as:Activity.

**Comment by azaroth42** [comment]
Right, I'm not suggesting that Object (or subClass) be sent, just some subset of the Activity subClasses.

For example:
```
source=http://example.org/activity/1&
target=http://example.com/post/2
```
Looks a lot like:
```
{
  "id": "http://example.org/activity/1",
  "object": "http://example.com/post/2"
}
```

That can still be verified by dereferencing the URI of the Activity, and could at the same time convey more (verifiable) information such as:

```
{
  "id": "http://example.org/activity/1",
  "type": "Like",
  "actor": {
    "type": "Person",
    "name": "Sally"
  },
  "object": "http://example.com/post/2"
}
```

Or similar.

**Comment by bblfish** [comment]
As activity streams has its own mime type, this solves one major problem of the lack of context of `application/x-www-form-urlencoded` mime types, though that can be answered as per issue #11 "Clarifying URLEncoded form meaning". 

It still requires the endpoint to declare the interpretation it will give to a POST, so that the side effects are properly understood. In this case I think the side-effects are negligible ( the server can make a few `GET` requests to verify the content, but those have no side effects ), so that an [LDP Basic Container](http://www.w3.org/TR/ldp/#dfn-linked-data-platform-basic-container) would be an appropriate type for the "endpoint".  But the client needs to know that there are no side-effects.

If Activity Streams had a pure JSON-LD mime type it would work immediately with LDP.

**Comment by azaroth42** [comment]
Some rationales for allowing additional, potentially verifiable information:
  * And endpoint can use the additional information for filtering.  If I only track Likes, then I can drop on the floor any request that does not have that type.  Or that I only track people I know, and hence will filter on actor.  This saves the verification round trip, which is expensive, for activities that are not of interest.
  * By adding authentication or known parties, the trackback problem is avoided, and thus verification would be unnecessary if all of the useful information is included in the request.
  * Interop with other systems, including but not limited to LDP.
  * Avoids the lack of semantics regarding form-encoded and simple keys by sending existing, well defined and described content, that has been developed as part of this WG.
  * Enables extensibility without fear of term collision, such as for Vouch.

**Comment by kevinmarks** [comment]
You don't know who sent the webmention, so you should only trust
information that you have verified by inspection.

On 27 Nov 2015 11:24 am, "Rob Sanderson" <notifications@github.com> wrote:
>
> Some rationales for allowing additional, potentially verifiable
information:
>
> And endpoint can use the additional information for filtering. If I only
track Likes, then I can drop on the floor any request that does not have
that type. Or that I only track people I know, and hence will filter on
actor. This saves the verification round trip, which is expensive, for
activities that are not of interest

If you drop on the floor anything without an as:like sent, you will be
dropping most likes. That's your prerogative, but may be confusing to those
sending likes without this extra payload.

> By adding authentication or known parties, the trackback problem is
avoided, and thus verification would be unnecessary if all of the useful
information is included in the request.

Indeed, but that would be a different protocol, closer to micropub.

> Interop with other systems, including but not limited to LDP.

Adding requirements reduces interoperability. We already have a robust
infrastructure for remapping other formats into webmentions.

> Avoids the lack of semantics regarding form-encoded and simple keys by
sending existing, well defined and described content, that has been
developed as part of this WG.

Again, that would be a different protocol.

> Enables extensibility without fear of term collision, such as for Vouch.
>

Are there any examples of actual term collision? Webmention is a simple
protocol for notification, it leaves negotiations on structure to the
source and endpoint.

**Comment by azaroth42** [comment]
Happy to close wontfix, given discussion. MicroPub or ActivityPump could fulfill these, without complicating webmention.

**Comment by aaronpk** [comment]
Closing based on discussion this morning: http://www.w3.org/2015/12/02-social-irc#T18-32-04

Once you start sending things that look like activities, it is easy to start imagining sending actual content in the payload, which makes this look like its own spec and adds a whole host of security concerns and additional complexity.
